<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Recruitment Applications Report</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 10pt; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #4e73df; padding-bottom: 10px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 8pt; color: #777; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #4e73df; color: white; text-align: left; padding: 8px; font-weight: bold; border: 1px solid #ddd; }
        td { padding: 8px; border: 1px solid #ddd; vertical-align: top; }
        tr:nth-child(even) { background-color: #f8f9fc; }
        .meta { margin-bottom: 20px; font-size: 9pt; }
        .badge { padding: 3px 6px; border-radius: 4px; font-size: 8pt; font-weight: bold; text-transform: uppercase; }
        .badge-primary { background-color: #4e73df; color: white; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Recruitment Applications Report</h1>
    </div>

    <div class="meta">
        <strong>Generated At:</strong> {{ $generated_at }}<br>
        <strong>Total Records:</strong> {{ $total_records }}
    </div>

    <table>
        <thead>
            <tr>
                @foreach($headers as $header)
                    <th>{{ ucwords(str_replace('_', ' ', $header)) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($data as $row)
                <tr>
                    @foreach($headers as $header)
                        <td>{{ $row[$header] ?? 'N/A' }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by MOM HR Management System | Page <span class="page-number"></span>
    </div>
</body>
</html>
